services:
  rabbitmq:
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    image: rabbitmq:3.13-management
    volumes:
      - ./rabbitmq/:/var/lib/rabbitmq/data
    restart: always
  postresql:
    container_name: postgresql
    ports:
      - 5432:5432
    image: postgres:15
    volumes:
      - ./postgres/:/var/lib/postgres/data
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=booking