spring:
  application:
    name: booking
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432}/booking
    username: ${DATASOURCE_USERNAME:postgres}
    password: ${DATASOURCE_PASSWORD:postgres}
  jpa:
    generate-ddl: true
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
server:
  port: 8081
rabbitmq:
  exchange:
    bookingDirectExchange: ${BOOKING_DIRECT_EXCHANGE:booking.direct}
  queue:
    bookingQueue: ${BOOKING_QUEUE:booking.queue}
    paymentQueue: ${PAYMENT_QUEUE:payment.queue}
    notificationQueue: ${NOTIFICATION_QUEUE:notification.queue}
  routingKey:
    bookingPaymentRoutingKey: ${BOOKING_PAYMENT_ROUTING_KEY:booking.payment}
    bookingNotificationRoutingKey: ${BOOKING_NOTIFICATION_ROUTING_KEY:booking.notification}