spring:
  application:
    name: booking
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432}/booking
    username: postgres
    password: postgres
  jpa:
    generate-ddl: true